App\Media\Domain\Model\Movie:
    attributes:
        id:
            groups:
                - read.movie
        title:
            groups:
                - read.movie
        releaseYear:
            groups:
                - read.movie
        director:
            groups:
                - read.movie
        overview:
            groups:
                - read.movie
