---
App\Music\Domain\Model\Song:
  properties:
    title:
      - Symfony\Component\Validator\Constraints\NotNull: ~
      - App\Music\Domain\Model\VO\Constraint\SongNameConstraint: ~
    duration:
      - App\Music\Domain\Model\VO\Constraint\DurationConstraint: ~
    album:
      - Symfony\Component\Validator\Constraints\NotNull: ~


App\Music\Domain\Input\SongInput:
  properties:
    title:
      - Symfony\Component\Validator\Constraints\NotNull: ~
      - App\Music\Domain\Model\VO\Constraint\SongNameConstraint: ~
    duration:
      - App\Music\Domain\Model\VO\Constraint\DurationConstraint: ~
