---
App\Media\Domain\Model\Genre:
  attributes:
    id:
      groups: [read]
    name:
      groups: [read, write, genre]


App\Media\Application\UseCase\Create\CreateGenre:
  attributes:
    name:
      groups: [write]


App\Media\Application\UseCase\Update\UpdateGenre:
  attributes:
    name:
      groups: [write]
