---
App\Media\Domain\Model\Movie:
  attributes:
    id:
      groups: [read]
    title:
      groups: [read, write, movie]
    releaseYear:
      groups: [read, write, movie]
    director:
      groups: [read, write, movie]
    reviews:
      groups: [read, write, movie]
    genres:
      groups: [read, write, movie]
    overview:
      groups: [read, write, movie]
    classification:
      groups: [read, write, movie]
    raw:
      groups: [read, write, movie]


App\Media\Application\UseCase\Create\CreateMovie:
  attributes:
    title:
      groups: [write]
    releaseYear:
      groups: [write]
    director:
      groups: [write]
    reviews:
      groups: [write]
    genres:
      groups: [write]
    overview:
      groups: [write]
    classification:
      groups: [write]
    raw:
      groups: [write]


App\Media\Application\UseCase\Update\UpdateMovie:
  attributes:
    title:
      groups: [write]
    releaseYear:
      groups: [write]
    director:
      groups: [write]
    reviews:
      groups: [write]
    genres:
      groups: [write]
    overview:
      groups: [write]
    classification:
      groups: [write]
    raw:
      groups: [write]
