---
App\Media\Domain\Model\Review:
  attributes:
    id:
      groups: [get.item, get.collection]
    review:
      max_depth: 1
      groups: [get.item, get.collection, post, put]
    score:
      max_depth: 1
      groups: [get.item, get.collection, post, put]
    movie:
      max_depth: 1
      groups: [get.item, get.collection, post, put]


App\Media\Domain\Input\ReviewInput:
  attributes:
    review:
      max_depth: 1
      groups: [post, put]
    score:
      max_depth: 1
      groups: [post, put]
    movie:
      max_depth: 1
      groups: [post, put]
