---
App\Media\Domain\Model\Review:
  attributes:
    id:
      groups: [read]
    review:
      groups: [read, write, review, movie]
    score:
      groups: [read, write, review, movie]
    movie:
      groups: [read]
