---
App\Auth\Domain\Model\User:
  attributes:
    id:
      groups: [read]
    username:
      groups: [read]
    email:
      groups: [read]
    roles:
      groups: [read]
    password:
      groups: [read]


App\Auth\Application\Input\UserInput:
  attributes:
    username:
      groups: [write]
    email:
      groups: [write]
    roles:
      groups: [write]
    password:
      groups: [write]
