version: "3.4"

# Production environment override
services:
  php:
    build:
      context: ./api
      target: frankenphp_prod
    environment:
      APP_SECRET: ${APP_SECRET}
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}

  http-cache:
    volumes:
      - ./api/frankenphp/cache/conf.d:/etc/nginx/conf.d
      - ./api/frankenphp/cache/lua/http-cache:/usr/local/openresty/luajit/share/lua/5.1/http-cache

  www:
     build:
      context: ./www
      target: prod

  admin:
    build:
      context: ./admin
      target: prod


  database:
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
