api_platform:
    title: Hello API Platform
    version: 1.0.0
    show_webby: false
    mapping:
        paths: [ '%kernel.project_dir%/config/mapping/api' ]
    
    formats:
        #html: [ 'text/html' ]
        jsonld: [ 'application/ld+json' ]
        #        jsonhal: [ 'application/hal+json' ]
        #        jsonapi: [ 'application/vnd.api+json' ]
        #        json: [ 'application/json' ]
    patch_formats:
        json: [ 'application/merge-patch+json' ]
    
    # Mercure integration, remove if unwanted
    mercure: ~
    
    http_cache:
        invalidation:
            enabled: true
#            varnish_urls: [ '%env(VARNISH_URL)%' ]
            varnish_urls: [ 'http://http-cache' ]
            purger: 'api_platform.http_cache.purger.varnish.xkey'
            xkey: 
                glue: ','
        public: true
    
    # Good cache defaults for REST APIs
    defaults:
        stateless: true
        pagination_client_items_per_page: true
        pagination_maximum_items_per_page: 50
        cache_headers:
            etag: false
#            max_age: 1000
            shared_max_age: 2592000
            vary: [ 'Content-Type', 'Authorization', 'Origin' ]
        
        extra_properties:
            standard_put: true


when@dev:
    api_platform:
        defaults:
            cache_headers:
                max_age: 0
                shared_max_age: 0
    
    
