api_platform:
    title: Hello API Platform
    version: 1.0.0
    show_webby: false
    mapping:
        paths: [ '%kernel.project_dir%/config/mapping/api' ]
    
    formats:
        jsonld: [ 'application/ld+json' ]
        #        jsonhal: [ 'application/hal+json' ]
        #        jsonapi: [ 'application/vnd.api+json' ]
        #        json: [ 'application/json' ]
        html: [ 'text/html' ]
    patch_formats:
        json: [ 'application/merge-patch+json' ]
    
    # Mercure integration, remove if unwanted
    mercure: ~
    
    exception_to_status:
        # The 4 following handlers are registered by default, keep those lines to prevent unexpected side effects
        Symfony\Component\Serializer\Exception\ExceptionInterface: 400 # Use a raw status code (recommended)
        ApiPlatform\Exception\InvalidArgumentException: !php/const Symfony\Component\HttpFoundation\Response::HTTP_BAD_REQUEST
        ApiPlatform\Exception\FilterValidationException: 400
        Doctrine\ORM\OptimisticLockException: 409

        # Validation exception
        ApiPlatform\Validator\Exception\ValidationException: !php/const Symfony\Component\HttpFoundation\Response::HTTP_UNPROCESSABLE_ENTITY

        # Custom mapping
#        PlanB\Framework\Doctrine\Criteria\InvalidFilterException: 500
        Exception: 500
        
    
    http_cache:
        invalidation:
            enabled: true
            varnish_urls: [ '%env(VARNISH_URL)%' ]
            purger: 'api_platform.http_cache.purger.varnish.ban'
        public: true
    
    # Good cache defaults for REST APIs
    defaults:
        stateless: true
        pagination_client_items_per_page: true
        pagination_maximum_items_per_page: 50
        cache_headers:
            etag: false
#            max_age: 1000
            shared_max_age: 2592000
            vary: [ 'Content-Type', 'Authorization', 'Origin' ]
        #            invalidation:
        #                xkey:
        #                    glue: ','
        
        extra_properties:
            standard_put: true


when@dev:
    api_platform:
        defaults:
            cache_headers:
                max_age: 0
                shared_max_age: 0
    
    
