api_platform:
    title: Hello API Platform
    version: 1.0.0
    show_webby: false
    mapping:
        paths: [ '%kernel.project_dir%/config/mapping/api' ]
    
    formats:
        jsonld: [ 'application/ld+json' ]
        #        jsonhal: [ 'application/hal+json' ]
        #        jsonapi: [ 'application/vnd.api+json' ]
        #        json: [ 'application/json' ]
        html: [ 'text/html' ]
    patch_formats:
        json: [ 'application/merge-patch+json' ]
    
    # Mercure integration, remove if unwanted
    mercure: ~
    
    http_cache:
        invalidation:
            enabled: true
            varnish_urls: [ '%env(VARNISH_URL)%' ]
            purger: 'api_platform.http_cache.purger.varnish.ban'
        public: true
    
    # Good cache defaults for REST APIs
    defaults:
        stateless: true
        pagination_client_items_per_page: true
        pagination_maximum_items_per_page: 50
        cache_headers:
            etag: false
            max_age: 0
            shared_max_age: 3600
            vary: [ 'Content-Type', 'Authorization', 'Origin' ]
        #            invalidation:
        #                xkey:
        #                    glue: ','
        
        extra_properties:
            standard_put: true
