framework:
    validation:
        email_validation_mode: html5
        enabled: true
        mapping:
            paths: [ '%kernel.project_dir%/config/mapping/validator' ]

when@test:
    framework:
        validation:
            not_compromised_password: false
