---
App\Music\Domain\Model\Disco:
  attributes:
    id:
      groups: [get.item, get.collection]
    title:
      groups: [get.item, get.collection]
    songs:
      groups: [get.item]


App\Music\Domain\Input\DiscoInput:
  attributes:
    id:
      groups: [post, put, write]
    title:
      groups: [post, put, write]
    songs:
      groups: [post, put, write]
