---
App\Music\Domain\Model\Song:
  attributes:
    id:
      groups: [get.item, get.collection]
    title:
      groups: [get.item, get.collection]
    duration:
      groups: [get.item, get.collection]
    album:
      groups: [get.item, get.collection]


App\Music\Domain\Input\SongInput:
  attributes:
    id:
      groups: [post, put]
    title:
      groups: [post, put]
    duration:
      groups: [post, put]
    album:
      groups: [post, put]
