doctrine:
    orm:
        mappings:
            Staff:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/mapping/doctrine/Staff'
                prefix: App\Staff\Domain\Model
    dbal:
        types:
            Staff.UserId: App\Staff\Framework\Doctrine\DBAL\UserIdDBALType
            Staff.UserName: App\Staff\Framework\Doctrine\DBAL\UserNameDBALType
            Staff.Email: App\Staff\Framework\Doctrine\DBAL\EmailDBALType
