---
App\Media\Application\UseCase\Create\CreateDirector:
  properties:
    name:
      - Symfony\Component\Validator\Constraints\NotNull: ~
      - App\Media\Domain\Model\VO\Constraint\FullNameConstraint: ~


App\Media\Application\UseCase\Update\UpdateDirector:
  properties:
    name:
      - Symfony\Component\Validator\Constraints\NotNull: ~
      - App\Media\Domain\Model\VO\Constraint\FullNameConstraint: ~
