---
App\Media\Application\UseCase\Create\CreateMovie:
  properties:
    title:
      - Symfony\Component\Validator\Constraints\NotNull: ~
      - App\Media\Domain\Model\VO\Constraint\MovieTitleConstraint: ~
    releaseYear:
      - Symfony\Component\Validator\Constraints\NotNull: ~
      - App\Media\Domain\Model\VO\Constraint\ReleaseYearConstraint: ~
    director:
      - Symfony\Component\Validator\Constraints\NotNull: ~
    reviews:
      - Symfony\Component\Validator\Constraints\NotNull: ~
    genres:
      - Symfony\Component\Validator\Constraints\Optional: ~
    overview:
      - Symfony\Component\Validator\Constraints\NotNull: ~
      - App\Media\Domain\Model\VO\Constraint\OverviewConstraint: ~
    classification:
      - Symfony\Component\Validator\Constraints\NotNull: ~
      - App\Media\Domain\Model\VO\Constraint\ClassificationConstraint: ~
    raw:
      - Symfony\Component\Validator\Constraints\NotNull: ~
      - App\Media\Domain\Model\VO\Constraint\ScoreConstraint: ~


App\Media\Application\UseCase\Update\UpdateMovie:
  properties:
    title:
      - Symfony\Component\Validator\Constraints\NotNull: ~
      - App\Media\Domain\Model\VO\Constraint\MovieTitleConstraint: ~
    releaseYear:
      - Symfony\Component\Validator\Constraints\NotNull: ~
      - App\Media\Domain\Model\VO\Constraint\ReleaseYearConstraint: ~
    director:
      - Symfony\Component\Validator\Constraints\NotNull: ~
    reviews:
      - Symfony\Component\Validator\Constraints\NotNull: ~
    genres:
      - Symfony\Component\Validator\Constraints\Optional: ~
    overview:
      - Symfony\Component\Validator\Constraints\NotNull: ~
      - App\Media\Domain\Model\VO\Constraint\OverviewConstraint: ~
    classification:
      - Symfony\Component\Validator\Constraints\NotNull: ~
      - App\Media\Domain\Model\VO\Constraint\ClassificationConstraint: ~
    raw:
      - Symfony\Component\Validator\Constraints\NotNull: ~
      - App\Media\Domain\Model\VO\Constraint\ScoreConstraint: ~
