---
App\Media\Domain\Input\ReviewInput:
  properties:
    review:
      - Symfony\Component\Validator\Constraints\NotNull: ~
      - App\Media\Domain\Model\VO\Constraint\ReviewContentConstraint: ~
    score:
      - Symfony\Component\Validator\Constraints\NotNull: ~
      - App\Media\Domain\Model\VO\Constraint\ScoreConstraint: ~
    movie:
      - Symfony\Component\Validator\Constraints\NotNull: ~
