App\Media\Application\UseCase\Create\CreateGenre:
    properties:
        name:
            -
                Symfony\Component\Validator\Constraints\NotNull: ~
            -
                App\Media\Domain\Model\VO\Constraint\GenreNameConstraint: ~
