---
services:
  _defaults:
    autowire: false
    autoconfigure: false
    public: false
  bookstore.book.filters.text:
    parent: planb.doctrine.orm.text_filter
    arguments:
      $properties:
        title: ~
    tags: [api_platform.filter]
