---
App\BookStore\Domain\Model\Tag:
  properties:
    name:
      - Symfony\Component\Validator\Constraints\NotNull: ~
      - App\BookStore\Domain\Model\VO\Constraint\TagNameConstraint: ~


App\BookStore\Domain\Input\TagInput:
  properties:
    name:
      - Symfony\Component\Validator\Constraints\NotNull: ~
      - App\BookStore\Domain\Model\VO\Constraint\TagNameConstraint: ~
