security:
    role_hierarchy:
        ROLE_MEDIA_GENRES_EDITOR:
            - ROLE_MEDIA_GENRES_LIST
            - ROLE_MEDIA_GENRES_CREATE
            - ROLE_MEDIA_GENRES_EDIT
            - ROLE_MEDIA_GENRES_DELETE
            - ROLE_MEDIA_GENRES_SHOW
        ROLE_MEDIA_MOVIES_EDITOR:
            - ROLE_MEDIA_MOVIES_LIST
            - ROLE_MEDIA_MOVIES_CREATE
            - ROLE_MEDIA_MOVIES_EDIT
            - ROLE_MEDIA_MOVIES_DELETE
            - ROLE_MEDIA_MOVIES_SHOW
        ROLE_MEDIA_REVIEWS_EDITOR:
            - ROLE_MEDIA_REVIEWS_LIST
            - ROLE_MEDIA_REVIEWS_CREATE
            - ROLE_MEDIA_REVIEWS_EDIT
            - ROLE_MEDIA_REVIEWS_DELETE
            - ROLE_MEDIA_REVIEWS_SHOW
        ROLE_MEDIA_DIRECTORS_EDITOR:
            - ROLE_MEDIA_DIRECTORS_LIST
            - ROLE_MEDIA_DIRECTORS_CREATE
            - ROLE_MEDIA_DIRECTORS_EDIT
            - ROLE_MEDIA_DIRECTORS_DELETE
            - ROLE_MEDIA_DIRECTORS_SHOW
        ROLE_MEDIA_EDITOR:
            - ROLE_MEDIA_GENRES_EDITOR
            - ROLE_MEDIA_MOVIES_EDITOR
            - ROLE_MEDIA_REVIEWS_EDITOR
            - ROLE_MEDIA_DIRECTORS_EDITOR
        ROLE_EDITOR:
            - ROLE_MEDIA_GENRES_EDITOR
            - ROLE_MEDIA_MOVIES_EDITOR
            - ROLE_MEDIA_REVIEWS_EDITOR
            - ROLE_MEDIA_DIRECTORS_EDITOR
            - ROLE_MEDIA_EDITOR
        ROLE_ADMIN:
            - ROLE_EDITOR
