security:
    role_hierarchy:
        ROLE_MEDIA_GENRES: [ROLE_MEDIA_GENRES_CREATE, ROLE_MEDIA_GENRES_LIST, ROLE_MEDIA_GENRES_EDIT, ROLE_MEDIA_GENRES_DELETE, ROLE_MEDIA_GENRES_SHOW]
        ROLE_MEDIA_MOVIES: [ROLE_MEDIA_MOVIES_CREATE, ROLE_MEDIA_MOVIES_LIST, ROLE_MEDIA_MOVIES_EDIT, ROLE_MEDIA_MOVIES_DELETE, ROLE_MEDIA_MOVIES_SHOW]
        ROLE_MEDIA_DIRECTORS: [ROLE_MEDIA_DIRECTORS_CREATE, ROLE_MEDIA_DIRECTORS_LIST, ROLE_MEDIA_DIRECTORS_EDIT, ROLE_MEDIA_DIRECTORS_DELETE, ROLE_MEDIA_DIRECTORS_SHOW]
        ROLE_EDITOR: [ROLE_MEDIA_GENRES, ROLE_MEDIA_MOVIES, ROLE_MEDIA_DIRECTORS]
        ROLE_ADMIN: [ROLE_EDITOR]
