App\Media\Application\UseCase\Create\CreateMovie:
    properties:
        title:
            -
                Symfony\Component\Validator\Constraints\NotNull: ~
            -
                App\Media\Domain\Model\VO\Constraint\MovieTitleConstraint: ~
        releaseYear:
            -
                Symfony\Component\Validator\Constraints\NotNull: ~
            -
                App\Media\Domain\Model\VO\Constraint\ReleaseYearConstraint: ~
        director:
            -
                Symfony\Component\Validator\Constraints\NotNull: ~
        overview:
            -
                Symfony\Component\Validator\Constraints\NotNull: ~
            -
                App\Media\Domain\Model\VO\Constraint\OverviewConstraint: ~
