kernel:
    resource: ../src/Kernel.php
    type: annotation

authentication_token:
    path: /api/token/auth
    methods: ['POST']

gesdinet_jwt_refresh_token:
    path: /api/token/refresh

token_logout:
    path: /api/token/logout
    
    
user_context_hash:
    path: /api/_fos_user_context_hash
    controller: \App\Auth\Framework\Controller\FosController
#[Route('/_fos_user_context_hash', name: 'user_context_hash')]
