App\Media\Application\UseCase\Create\CreateMovie:
    attributes:
        title:
            groups:
                - create.movie
        releaseYear:
            groups:
                - create.movie
        director:
            groups:
                - create.movie
        overview:
            groups:
                - create.movie
