---
App\BookStore\Domain\Model\Author:
  attributes:
    id:
      groups: [get.item, get.collection]
    name:
      groups: [get.item, get.collection]


App\BookStore\Domain\Input\AuthorInput:
  attributes:
    id:
      groups: [post, put]
    name:
      groups: [post, put]
