---
App\BookStore\Domain\Model\Author:
  attributes:
    id:
      groups: [read.bookstore.author, read.bookstore.book]
    name:
      groups: [read.bookstore.author, read.bookstore.book]


App\BookStore\Application\Input\AuthorInput:
  attributes:
    name:
      groups: [write.bookstore.author]
