---
App\BookStore\Domain\Model\Book:
  attributes:
    id:
      groups: [get.item, get.collection]
    title:
      groups: [get.item, get.collection]
    price:
      groups: [get.item, get.collection]
    author:
      groups: [get.item, get.collection]
    tags:
      groups: [get.item, get.collection]


App\BookStore\Domain\Input\BookInput:
  attributes:
    id:
      groups: [post, put]
    title:
      groups: [post, put]
    price:
      groups: [post, put]
    author:
      groups: [post, put]
    tags:
      groups: [post, put]
