---
App\BookStore\Domain\Model\Book:
  attributes:
    id:
      groups: [read.bookstore.book]
    title:
      groups: [read.bookstore.book]
    price:
      groups: [read.bookstore.book]
    author:
      groups: [read.bookstore.book]


App\BookStore\Application\Input\BookInput:
  attributes:
    title:
      groups: [write.bookstore.book]
    price:
      groups: [write.bookstore.book]
    author:
      groups: [write.bookstore.book]
