---
App\BookStore\Domain\Model\Tag:
  attributes:
    id:
      groups: [get.item, get.collection]
    name:
      groups: [get.item, get.collection]


App\BookStore\Domain\Input\TagInput:
  attributes:
    id:
      groups: [post, put]
    name:
      groups: [post, put]
