App\Media\Domain\Model\Movie:
    attributes:
        id:
            groups:
                - search.movie
                - read
        title:
            groups:
                - search.movie
                - read
        releaseYear:
            groups:
                - search.movie
                - read
        director:
            groups:
                - search.movie
                - read
        overview:
            groups:
                - search.movie
                - read
